### ISSUE TITLE
Add a section with job offers

### ISSUE THREAD

**Issue by laannili** [fs-linguistics/fs-linguistics.github.io#52]
I think a job offer section on our website about current job offers, hiwi positions or internships would be great.

We could populate this space with the job offers that are sent around by professors and secretary. Additionally, if we communicate this site to our teachers, they could use it to advertise Hiwi positions within our institute that until now are usually staffed on a rather informal and intransparent basis (mouth-to-mouth propaganda etc).

Once this page is created it might attract other positions. The important point will be to have one person allocated to it to maintain the content.

I‘d volunteer to take over responsibility for this section but would be glad to hear your ideas and thoughts concerning the whole concept.

**Comment by noc-tae** [comment]
I've finally done this
