### ISSUE TITLE
Redo calendar

### ISSUE THREAD

**Issue by laannili** [fs-linguistics/fs-linguistics.github.io#53]
Add a „real“ calendar with monthly overview and links & info to events that are going on e.g. workshops, information events, exams (?), parties, FS events (ofc) - you name it.

As for the job offer page, here it is also essential that the page it up-to-date and maintained.

**Comment by noc-tae** [comment]
We can embed a Google Calendar fairly easily: https://support.google.com/calendar/answer/41207?hl=en

**Comment by laannili** [comment]
For the protocol: Nicolai and Annika maintain the calendar - everyone is welcome to suggest events that should be added.

**Comment by noc-tae** [comment]
Public link: https://calendar.google.com/calendar/embed?src=b8b5e3308a11d1f02ea9a710a07116117b568951be60f5325846200d09ae9f25%40group.calendar.google.com&ctz=Europe%2FBerlin

iCal Link: https://calendar.google.com/calendar/ical/b8b5e3308a11d1f02ea9a710a07116117b568951be60f5325846200d09ae9f25%40group.calendar.google.com/public/basic.ics

**Comment by jzw2** [comment]
Should I we close this one, or do we want to improve the calendar more?

**Comment by noc-tae** [comment]
I think we can close this issue—we have the calendar
